context:
  version: "4.6.8"

package:
  name: dotnet-outdated
  version: ${{ version }}

source:
  url: https://github.com/dotnet-outdated/dotnet-outdated/archive/v${{ version }}.tar.gz
  sha256: 977bf77caf6f9759cff4fb80e9eef0bbfd579875c1dcd8cd65c6cabbad2448ca

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-outdated --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A .NET Core global tool to display and update outdated NuGet packages in a project
  homepage: https://github.com/dotnet-outdated/dotnet-outdated
  repository: https://github.com/dotnet-outdated/dotnet-outdated

extra:
  recipe-maintainers:
    - danielnachun
